<?php echo $this->render("layouts/header.phtml"); ?>
<h3>Remove Artist </h3>
<table>
	<tr>
		<td>Artists - <i>Total Artists (<?php echo $this->totalArtist; ?>)</i></td>
	</tr>
	<?php foreach($this->artists as $artist){ ?>
		<tr><td><input type="checkbox" value="<?php echo $this->escape($artist['name'])?>"
			name="remove" /><?php echo $artist['name']?>
			<?php if($artist['rating'] == 5){ ?> * <?php } ?></td></tr>
		<?php } ?>
		<tr><td><input type="submit" value="Remove"/></td></tr>
	</table>
	<?php echo $this->render("layouts/footer.phtml"); ?>
