<html>
<title>The react experiment</title>
<head>
	<!-- <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen, projection"> -->
	<!-- <script type="text/javascript" src="/src/Routes.js"></script> -->
	<?php
	// var_dump($this->getScriptPath());
	// var_dump(get_class_methods($this->headScript()));
	$this->headLink()->prependStylesheet("/css/style.css");
	$this->headLink()->prependStylesheet("/bootstrap/css/bootstrap.min.css");
	$this->headScript()->appendFile('/src/containers/Login.js', 'text/babel');
	$this->headScript()->appendFile('/bootstrap/js/bootstrap.min.js', 'text/javascript');
	?>
	<?= $this->headLink(); ?>
</head>
<body>
	<h1>Hello react</h1>
	<div id="root">
	</div>
</body>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.1.19/browser.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://fb.me/react-with-addons-0.14.3.js"></script>
<script src="https://fb.me/react-dom-0.14.3.js"></script>
	<?= $this->headScript(); ?>
</html>
